# Generated by Django 4.2.6 on 2023-11-14 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_vehcle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(blank=True, max_length=200)),
                ('parking_Area_no', models.CharField(max_length=200)),
                ('vheicle_type', models.CharField(max_length=200)),
                ('status', models.BooleanField()),
                ('arrival_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_Area_no', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(max_length=200)),
                ('vehicle_limit', models.CharField(max_length=100)),
                ('parking_charge', models.CharField(max_length=200)),
                ('status', models.BooleanField()),
                ('doc', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
