# Generated by Django 4.2.6 on 2024-07-09 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking_system', '0002_alter_category_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_vehcle',
            name='parking_Area_no',
        ),
        migrations.RemoveField(
            model_name='add_vehcle',
            name='vheicle_type',
        ),
        migrations.AddField(
            model_name='add_vehcle',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parking_system.category'),
        ),
    ]
