# Generated by Django 4.2.6 on 2024-07-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_system', '0003_remove_add_vehcle_parking_area_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_vehcle',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
