# Generated by Django 4.2.6 on 2024-07-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_system', '0004_alter_add_vehcle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='vehicle_count',
            field=models.IntegerField(default=0),
        ),
    ]
