# Generated by Django 4.2.6 on 2024-07-11 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking_system', '0005_category_vehicle_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('arrival_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='doc',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='add_vehcle',
        ),
        migrations.AddField(
            model_name='addvehicle',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_system.category'),
        ),
    ]
