# Generated by Django 4.2.6 on 2024-07-11 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_system', '0006_addvehicle_alter_category_doc_alter_category_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addvehicle',
            old_name='category',
            new_name='categories',
        ),
    ]
